ITEM.name = "Kalashnikov Concern AKM"
ITEM.description = "Introduced into service with the Soviet Army in 1959, the AKM is the most ubiquitous variant of the entire AK series of firearms and it has found widespread use with most member states of the former Warsaw Pact and its African and Asian allies as well as being widely exported and produced in many other countries. The production of these rifles was carried out at both the Tula Arms Plant and Izhmash. It was officially replaced in Soviet frontline service by the AK-74 in the late 1970s, but remains in use worldwide. Fires 7.62x39 rounds."
ITEM.model = "models/weapons/ethereal/w_akmconc.mdl"
ITEM.class = "cw_kk_ins2_akmconc"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 49750
ITEM.weight = 7