ITEM.name = "AK-12"
ITEM.description= "The AK-12, also known as the AK-200, is the newest member of the AK family. While the Russian army had no interest in purchasing any of these because of their massive supply of AK-74's, the AK-12 is still a highly modular and effective weapon platform."
ITEM.model = "models/weapons/ethereal/w_ak12.mdl"
ITEM.class = "cw_kk_ins2_ak12"
ITEM.weaponCategory = "primary"
ITEM.width = 4 
ITEM.height = 2
ITEM.price = 42000
ITEM.weight = 8