ITEM.name = "AK-103"
ITEM.description = "The AK-103 assault rifle is a derivative of the AK-74M chambered for the 7.62×39mm M43 round, similar to the older AKM. The AK-103 can be fitted with a variety of sights, including night vision and telescopic sights, plus a knife-bayonet or a grenade launcher. It uses plastic components where possible instead of wood or metal, with such components being the pistol grip, handguards and stock."
ITEM.model = "models/weapons/ethereal/w_f_ak103.mdl"
ITEM.class = "cw_kk_ins2_ak103"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 32000
ITEM.weight = 7