ITEM.name = "AKM"
ITEM.description = "The AKM is an assault rifle firing the 7.62×39mm Soviet intermediate cartridge.\n\nAmmo: 7.62x39mm\nMagazine Capacity: 30"
ITEM.model = "models/weapons/ethereal/item_akm.mdl"
ITEM.class = "cw_kk_ins2_akm"
ITEM.weaponCategory = "primary"
ITEM.width = 4 
ITEM.height = 2
ITEM.price = 28000
ITEM.weight = 7