ITEM.name = "AS Val"
ITEM.description= "A silenced special forces assault rifle chambered for 9x39mm."
ITEM.model = "models/weapons/ethereal/w_asval.mdl"
ITEM.class = "cw_kk_ins2_asval"
ITEM.weaponCategory = "primary" 
ITEM.width = 4
ITEM.height = 2
ITEM.price = 84000
ITEM.weight = 8