ITEM.name = "CZ-805"
ITEM.description = "The CZ 805 was created, along with several variants of the rifle, by Česká zbrojovka Uherský Brod in 2006 to replace the Sa vz. 58 in the Czech Army. The CZ 805 BREN is used by the Czech military, Indonesian special forces and Mexican police. In 2014, Slovak Army began to replace its vz. 58 rifles with CZ 805. Fires 5.56x45 rounds."
ITEM.model = "models/weapons/ethereal/w_cz805.mdl"
ITEM.class = "cw_kk_ins2_cz805"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 42000
ITEM.weight = 9