ITEM.name = "Daewoo K2"
ITEM.description = "This rifle was developed by the South Korean Agency for Defense Development and manufactured by S&T Motiv (formerly Daewoo Precision Industries). It is currently the standard service rifle of the Republic of Korea Armed Forces. Fires 5.56x45 rounds."
ITEM.model = "models/weapons/ethereal/w_k2.mdl"
ITEM.class = "cw_kk_ins2_k2"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 35000
ITEM.weight = 7