ITEM.name = "FN FNP-45"
ITEM.description = "The FN FNP pistol is a series of semi-automatic, polymer-framed pistols manufactured in Columbia, South Carolina, by FNH USA, a division of Fabrique Nationale de Herstal. The pistol debuted in early 2006 and is chambered for the 9×19mm Parabellum, .40 S&W, .45 ACP, and .357 SIG cartridges."
ITEM.model = "models/weapons/ethereal/w_fnp.mdl"
ITEM.class = "cw_kk_ins2_fnp"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5300
ITEM.weight = 2