ITEM.name = "HK G36"
ITEM.description = "A black fully automatic assault rifle.\n\nAmmo: 5.56x45mm \nMagazine Capacity: 30"
ITEM.model = "models/weapons/g36/w_g36.mdl"
ITEM.class = "cw_kk_ins2_g36"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 45000
ITEM.weight = 7