ITEM.name = "G3A3"
ITEM.description= "A battle rifle that fires 7.62x51mm rounds."
ITEM.model = "models/weapons/ethereal/w_g3a3.mdl"
ITEM.class = "cw_kk_ins2_g3a3"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 2
ITEM.price = 90000
ITEM.weight = 10