ITEM.name = "Groza"
ITEM.description = "The OTs-14 Groza is a Russian selective fire bullpup assault rifle chambered for the 7.62×39 round and the 9×39mm subsonic round. It was developed in the 1990s at the TsKIB SOO in Tula, Russia. The weapon is colloquially known as OC-14 or OTs-14 'Groza'. This one is chambered in 7.62x39mm."
ITEM.model = "models/weapons/ethereal/item_groza1.mdl"
ITEM.class = "cw_kk_ins2_groza1"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 40000
ITEM.weight = 8