ITEM.name = "Galil"
ITEM.description = "The Galil is a family of Israeli small arms designed by Yisrael Galil and Yaacov Lior in the late 1960s and produced by Israel Military Industries (IMI) of Ramat HaSharon. The rifle design borrows heavily from the RK-62 and has a modified gas diversion system similar to the RK-62 to reduce the recoil of the rifle making it easier to fire especially in automatic mode."
ITEM.model = "models/weapons/ethereal/w_galil.mdl"
ITEM.class = "cw_kk_ins2_galil"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 40000
ITEM.weight = 8