ITEM.name = "S&W M10 Revolver"
ITEM.description = "The Smith & Wesson Model 10 is a revolver of worldwide popularity. It was the successor to the Smith & Wesson .32 Hand Ejector Model of 1896 and was the first Smith & Wesson revolver to feature a cylinder release latch on the left side of the frame like the Colt M1889. In production since 1899, it is a six-shot double-action .38 revolver with fixed sights."
ITEM.model = "models/weapons/ethereal/w_38rev.mdl"
ITEM.class = "cw_kk_ins2_revolver"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 800
ITEM.weight = 2