ITEM.name = "M1911"
ITEM.description = "An American military surplus semi-automatic pistol chambered for .45 ACP."
ITEM.model = "models/weapons/ethereal/w_1911.mdl"
ITEM.class = "cw_kk_ins2_m1911"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 2800
ITEM.weight = 3