ITEM.name = "M4A1"
ITEM.description = "The M4A1 carbine is a fully automatic variant of the basic M4 carbine intended for special operations use. The M4A1 was introduced in May 1991, and was in service in 1994. The M4A1 has a 'S-1-F' (safe/semi-automatic/fully automatic) trigger group, while the M4 has a 'S-1-3' (safe/semi-automatic/3-round burst) trigger group. Fires 5.56x45 rounds."
ITEM.model = "models/weapons/ethereal/w_m4a1.mdl"
ITEM.class = "cw_kk_ins2_m4a1"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 44000
ITEM.weight = 6