ITEM.name = "M249"
ITEM.description = "The M249 is the American adaptation of the Belgian FN Minimi, a light machine gun manufactured by the Belgian company FN Herstal (FN). The M249 is manufactured in the United States by the local subsidiary FN Manufacturing LLC in South Carolina and is widely used in the U.S. Armed Forces. Fires 5.56 Rounds."
ITEM.model = "models/weapons/ethereal/w_m249.mdl"
ITEM.class = "cw_kk_ins2_m249"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 3
ITEM.price = 95000
ITEM.weight = 22