ITEM.name = "M590"
ITEM.description = "The Mossberg 590 is a variant of the Mossberg 500 series, specifically made to be easier to field strip for cleaning, as well as being simpler to repair internal damage. Fires 12 Gauge shells."
ITEM.model = "models/weapons/ethereal/w_m590.mdl"
ITEM.class = "cw_kk_ins2_m590"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 13500
ITEM.weight = 8