ITEM.name = "M4 Spectre"
ITEM.description = "The Spectre is a compact and light weapon, designed for instant firepower in close combat at short ranges. The four models have top-folding buttstocks, and were available with or without a forward handgrip ahead of the magazine housing. The largely steel Spectre has a polymer overmolded grip, magazine release and safety/selector levers."
ITEM.model = "models/weapons/ethereal/w_m4spec.mdl"
ITEM.class = "cw_kk_ins2_m4spec"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 34000
ITEM.weight = 6