ITEM.name = "MR96"
ITEM.description= "A double-action revolver chambered for .44 Magnum."
ITEM.model = "models/weapons/ethereal/w_mr96.mdl"
ITEM.class = "cw_kk_ins2_mr96"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 15000
ITEM.weight = 3