ITEM.name = "Mossberg 88"
ITEM.description = "The Maverick 88 is a pump action shotgun manufactured by O.F. Mossberg & Sons. The Maverick 88 is virtually identical to the Mossberg 500. Factory Maverick 88s feature a black, synthetic only stock and forearm, cylinder bore (although interchangeable chokes are available on some hunting models), and cross-bolt safety. Most accessories are interchangeable with a Mossberg 500."
ITEM.model = "models/weapons/ethereal/w_chaser13.mdl"
ITEM.class = "cw_kk_ins2_chaser13"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 4400
ITEM.weight = 6