ITEM.name = "MK18"
ITEM.description = "A Close-Quarters weapon, the MK18 is a performance-built M4A1 with a shorter upper reciever and adjustable stock meant to be used by special units who have a need for reliable firepower in close to medium range engagements. Fires 5.56x45 Rounds."
ITEM.model = "models/weapons/ethereal/w_mk18.mdl"
ITEM.class = "cw_kk_ins2_mk18"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 60000
ITEM.weight = 6