ITEM.name = "Makarov"
ITEM.description = "A Russian steel-framed police pistol that fires 9x18 Makarov."
ITEM.model = "models/weapons/ethereal/w_makarov.mdl"
ITEM.class = "cw_kk_ins2_makarov"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 400
ITEM.weight = 2