ITEM.name = "Obrez"
ITEM.description= "A well-used sawn-off Mosin Nagant rifle, it's exact model is unclear."
ITEM.model = ("models/weapons/obrez/w_obrez.mdl")
ITEM.class = "cw_kk_ins2_obrez"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 8000
ITEM.weight = 7