ITEM.name = "PKP Pecheneg"
ITEM.description = "The PKP Pecheneg is a Russian 7.62×54mmR general-purpose machine gun. It is said to be more accurate than all its predecessors due to a heavier, non-removable, forced-air-cooling barrel with radial cooling ribs and a handle which eliminates the haze effect from hot gases and keeps the barrel cooler, making the weapon more reliable. Furthermore, the weapon is capable of having a telescopic sight or other sights mounted on it, increasing its accuracy and effective range. Uses 7.62x54mmR Belts."
ITEM.model = "models/weapons/ethereal/w_pkp.mdl"
ITEM.class = "cw_kk_ins2_pkp"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 3
ITEM.price = 80000
ITEM.weight = 30