ITEM.name = "FN P90"
ITEM.description = "A sub machine gun chambered in 5.7x28mm."
ITEM.model = "models/weapons/ethereal/w_p90.mdl"
ITEM.class = "cw_kk_ins2_p90"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 46000
ITEM.weight = 6