ITEM.name = "OTs-33 Pernach"
ITEM.description = "The OTs-33 Pernach is a Russian 9x18 Makarov machine pistol, derived from the 5.45mm OTs-23 Drotik machine pistol. The Pernach is an automatic pistol designed to replace the Stechkin APS in various special OMON units within the Russian police, the Russian Ministry of Internal Affairs (MVD) and other paramilitary units."
ITEM.model = "models/weapons/ethereal/w_pernach.mdl"
ITEM.class = "cw_kk_ins2_pernach"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.weight = 3