ITEM.name = "P99"
ITEM.description = "A German handgun, firing the 9x19mm cartridge."
ITEM.model = "models/weapons/ethereal/w_p99.mdl"
ITEM.class = "cw_kk_ins2_p99"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 3400
ITEM.weight = 2