ITEM.name = "QBZ-03"
ITEM.description = "An assault rifle that fires 5.56x45mm rounds."
ITEM.model = "models/weapons/qbz03/w_qbz03.mdl"
ITEM.class = "cw_kk_ins2_qbz03"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 55000
ITEM.weight = 8