ITEM.name = "RPK"
ITEM.description = "A long-barreled AK with a heavy stock. Fires 5.45x39mm."
ITEM.model = "models/weapons/ethereal/w_rpk.mdl"
ITEM.class = "cw_kk_ins2_rpk"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 2
ITEM.price = 46500
ITEM.weight = 11