ITEM.name = "SCAR-L"
ITEM.description = "The FN SCAR is a gas-operated self-loading rifle with a rotating bolt. It is constructed to be extremely modular, including barrel change to switch between calibers. The rifle was developed by Belgian manufacturer FN Herstal (FNH) for the United States Special Operations Command (SOCOM) to satisfy the requirements of the SCAR competition. The 'L' varient is chambered for 5.56x45mm Rounds, and has a standard length barrel for short-medium range combat."
ITEM.model = "models/weapons/ethereal/w_sca.mdl"
ITEM.class = "cw_kk_ins2_scarl"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 43250
ITEM.weight = 7