ITEM.name = "KAC Stoner LMG-A1"
ITEM.description = "A LMG variant of the Stoner rifle."
ITEM.model = "models/weapons/stonerlmg/w_stonerlmg.mdl"
ITEM.class = "cw_kk_ins2_stonerlmg"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 2
ITEM.price = 105000
ITEM.weight = 14