ITEM.name = "Saiga Semi-Automatic Rifle"
ITEM.description= "A civillian semi-automatic rifle. Fires 7.62x39mm."
ITEM.model = "models/weapons/ethereal/w_saiga762.mdl"
ITEM.class = "cw_kk_ins2_saiga762"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 9500
ITEM.weight = 8