ITEM.name = "SA58"
ITEM.description = "A battle rifle that fires 7.62x51mm rounds."
ITEM.model = "models/weapons/sa58/w_sa58.mdl"
ITEM.class = "cw_kk_ins2_sa58"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 85000
ITEM.weight = 8