ITEM.name = "USP .45"
ITEM.description = "The USP is a semi-automatic pistol developed in Germany by Heckler & Koch GmbH (H&K) of Oberndorf am Neckar as a replacement for the P7 series of handguns. This particular variant is chambered for the .45 ACP Round."
ITEM.model = "models/weapons/ethereal/w_usp45.mdl"
ITEM.class = "cw_kk_ins2_usp45"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4800
ITEM.weight = 2