ITEM.name = "Vector"
ITEM.description = "The KRISS Vector series are a family of weapons based upon the parent submachine gun design developed by KRISS USA, formerly Transformational Defense Industries (TDI). They use an unconventional delayed blowback system combined with in-line design to reduce perceived recoil and muzzle climb. This particular variant is chambered in .45 ACP."
ITEM.model = "models/weapons/ethereal/w_vector.mdl"
ITEM.class = "cw_kk_ins2_vector"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 36100
ITEM.weight = 7