ITEM.name = "CS-3a"
ITEM.model ="models/stalker/outfit/cs_light.mdl"
ITEM.replacements ="models/nasca/stalker/male_cs3a.mdl"
ITEM.description= "A CS-3a suit."
ITEM.longdesc = "A pair of reinforced tactical pants, comfortable nomex jacket and a plate carrier with pouches, it's a bare minimum of equipment for a seasoned merc, faction soldier or professional bandit."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 74800
ITEM.flag = "f"
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.artifactcontainers = {"3"}
ITEM.img = Material("vgui/hud/cs2.png")
ITEM.weight = 12
ITEM.res = {
	["Bullet"] = 0.50,
	["Blast"] = 0.40,
	["Fall"] = 0.40,
	["Burn"] = 0.35,
	["Radiation"] = 0.50,
	["Chemical"] = 0.50,
	["Shock"] = 0.35,
	["Psi"] = 0.40,
}