ITEM.name ="CS-1"
ITEM.model ="models/stalker/outfit/cs_light.mdl"
ITEM.replacements ="models/nasca/stalker/male_cs1a.mdl"
ITEM.description="A CS-1 suit."
ITEM.longdesc = "A pair of jeans, a rain jacket and a kevlar vest with lots of pouches. Another type of stalker 'uniform', made from off-the-shelf products. This one seems to have a high quality kevlar package."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 37400
ITEM.flag = "f"
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.artifactcontainers = {"1"}
ITEM.img = Material("vgui/hud/cs1.png")
ITEM.weight = 10
ITEM.res = {
	["Bullet"] = 0.20,
	["Blast"] = 0.20,
	["Fall"] = 0.20,
	["Burn"] = 0.25,
	["Radiation"] = 0.40,
	["Chemical"] = 0.40,
	["Shock"] = 0.25,
	["Psi"] = 0.00,
}