ITEM.name = "Expedition"
ITEM.model ="models/stalker/outfit/cs_light.mdl"
ITEM.replacements ="models/nasca/stalker/male_expedition.mdl"
ITEM.description= "An Expedition suit."
ITEM.longdesc = "A set of NBC gear and assault vest favored by Kiev's Berkut police unit. This SWAT outfit most likely made it's way into the Zone thanks to widespread corruption within ministry of internal affairs."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 68200
ITEM.flag = "b"
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.artifactcontainers = {"3"}
ITEM.img = Material("vgui/hud/io7a.png")
ITEM.weight = 15
ITEM.res = {
	["Bullet"] = 0.40,
	["Blast"] = 0.50,
	["Fall"] = 0.50,
	["Burn"] = 0.50,
	["Radiation"] = 0.20,
	["Chemical"] = 0.20,
	["Shock"] = 0.20,
	["Psi"] = 0.30,
}