ITEM.name = "IO8-A"
ITEM.model ="models/stalker/outfit/merc.mdl"
ITEM.replacements ="models/nasca/stalker/male_eagle_lone.mdl"
ITEM.description= "An IO8-A."
ITEM.longdesc = "Assembly of a light Russian vest, tactical fatigues and riot armor, most useful to a hunter or warfighter on a budget. Productions vary wildly in colors and sources of equipment. The vest stops some assault rifle rounds, but the protection is still relatively subpar."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 64900
ITEM.flag = "b"
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.artifactcontainers = {"1"}
ITEM.img = Material("vgui/hud/io7a.png")
ITEM.weight = 17
ITEM.addWeight = 22
ITEM.res = {
	["Bullet"] = 0.40,
	["Blast"] = 0.50,
	["Fall"] = 0.50,
	["Burn"] = 0.40,
	["Radiation"] = 0.20,
	["Chemical"] = 0.20,
	["Shock"] = 0.20,
	["Psi"] = 0.25,
}