ITEM.name = "Midnight" 
ITEM.replacements = "models/nasca/stalker/male_midnight_lone.mdl"
ITEM.model = "models/stalker/outfit/sunrise.mdl"
ITEM.description = "A Midnight suit."
ITEM.longdesc = "This suit is practically identicial in all ways to the PS5-M Universial Protection. However, it is slightly less effective overall due to the lower quality materials used to produce it."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 41800
ITEM.flag = "b"
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.artifactcontainers = {"1"}
ITEM.weight = 27
ITEM.addWeight = 31
ITEM.res = {
	["Bullet"] = 0.40,
	["Blast"] = 0.35,
	["Fall"] = 0.35,
	["Burn"] = 0.20,
	["Radiation"] = 0.20,
	["Chemical"] = 0.35,
	["Shock"] = 0.20,
	["Psi"] = 0.00,
}