ITEM.name = "PSZ-9d" 
ITEM.replacements = "models/nasca/stalker/male_psz12d_duty.mdl"
ITEM.model = "models/stalker/outfit/dolg_heavy.mdl"
ITEM.description = "PSZ-9d body armor."
ITEM.longdesc = "This early model of the Duty bodysuit is the Spetsnaz PSZ-9 body armor modified for the Zone. The suit is capable of stopping a rifle bullet, however, this level of protection comes at the cost of its weight, bulkiness and virtually non-existent anomaly protection. The suit cannot be modified with an artifact container, but may be upgraded with a combat support system."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 85800
ITEM.flag = "f"
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.artifactcontainers = {"0"}
ITEM.weight = 44
ITEM.addWeight = 35
ITEM.res = {
	["Bullet"] = 0.50,
	["Blast"] = 0.70,
	["Fall"] = 0.70,
	["Burn"] = 0.70,
	["Radiation"] = 0.20,
	["Chemical"] = 0.20,
	["Shock"] = 0.20,
	["Psi"] = 0.40,
}