ITEM.name = "Trenchcoat"
ITEM.replacements = "models/nasca/stalker/male_trenchcoat.mdl"
ITEM.model = "models/stalker/outfit/bandit3.mdl"
ITEM.description = "A trenchcoat."
ITEM.longdesc = "A regular leather trench coat. Has no special purpose other than to keep the wearer warm at night or protect from a blind dog bite. Although the trench coat is not particularly comfortable, it is often used by Bandits in the Zone - either because it allows them to hide in the dark or simply due to its 'cool' appearance."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 5400
ITEM.flag = "a"
ITEM.isHelmet = false
ITEM.isGasmask = false
ITEM.artifactcontainers = {"0"}
ITEM.img = Material("vgui/hud/trenchcoat.png")
ITEM.weight = 16
ITEM.addWeight = 11
ITEM.res = {
	["Bullet"] = 0.00,
	["Blast"] = 0.05,
	["Fall"] = 0.05,
	["Burn"] = 0.15,
	["Radiation"] = 0.00,
	["Chemical"] = 0.15,
	["Shock"] = 0.15,
	["Psi"] = 0.00,
}