ITEM.name = ".22LR"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.ammo = ".22LR"
ITEM.ammoAmount = 300
ITEM.description = "This small .22LR round is primarily used for pest control, but also sports shooting and entry-level shooting."
ITEM.weight = 0.012
ITEM.isAmmo = true
ITEM.category = "Ammunition"
ITEM.ammoPerBox = 100
ITEM.price = 50
ITEM.weight = 0.024