ITEM.name = "23mm Shells"
ITEM.model = "models/Items/BoxBuckshot.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "23mm Shell"
ITEM.description = "A Box that contains 23mm Buckshot shells."
ITEM.category = "Ammunition"
ITEM.ammoAmount = 45
ITEM.isAmmo = true
ITEM.ammoPerBox = 15
ITEM.price = 600
ITEM.weight = 0.2