ITEM.name = ".44 Magnum"
ITEM.model = "models/Items/357ammo.mdl"
ITEM.ammo = ".44 Magnum"
ITEM.ammoAmount = 150
ITEM.description = "This large-bore .44 Magnum cartridge was originally designed for revolvers, but quickly adopted by rifles and carbines."
ITEM.width = 2
ITEM.isAmmo = true
ITEM.category = "Ammunition"
ITEM.ammoPerBox = 30
ITEM.price = 350
ITEM.weight = 0.046