ITEM.name = "5.7x28mm"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.ammo = "5.7x28MM"
ITEM.ammoAmount = 150
ITEM.description = "The FN 5.7x28mm is a high velocity cartridge designed and manufactured by FN Herstal. It is a bottlenecked centerfire cartridge that is somewhat similar to the .22 Hornet or .22 K-Hornet. The 5.7x28mm was developed in conjunction with the FN P90 personal defense weapon (PDW) and FN Five-seven pistol, in response to NATO requests for a replacement for the 9x19mm Parabellum cartridge."
ITEM.isAmmo = true
ITEM.category = "Ammunition"
ITEM.ammoPerBox = 50
ITEM.price = 650
ITEM.weight = 0.016