ITEM.name = "9x18mm"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.ammo = "9x18MM"
ITEM.ammoAmount = 150
ITEM.description= "This 9x18mm round contains full metal jacket rounds with a steel penetrator and a lead core under a metal jacket."
ITEM.isAmmo = true
ITEM.category = "Ammunition"
ITEM.ammoPerBox = 50
ITEM.price = 65
ITEM.weight = 0.032