ITEM.name = "9x19mm"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.ammo = "9x19MM"
ITEM.ammoAmount = 150
ITEM.description = "This basic 9x19 caliber round with a jacketed bullet has good characteristics while being simple to produce. The round is popular due to the fact that international conventions prohibit the use of expanding ammunition in combat."
ITEM.isAmmo = true
ITEM.category = "Ammunition"
ITEM.ammoPerBox = 50
ITEM.price = 100
ITEM.weight = 0.042