ITEM.name = "M203 Grenade"
ITEM.model = ("models/Items/AR2_Grenade.mdl")
ITEM.description = "An M203 Grenade, made specifically to be launched from NATO Grenade Launchers."
ITEM.category = "Ammunition"
ITEM.ammo = "40MM"
ITEM.ammoAmount = 3
ITEM.isAmmo = true
ITEM.ammoPerBox = 1
ITEM.price = 2500
ITEM.weight = 0.46