ITEM.name = "PG-7VM Grenade"
ITEM.model = "models/weapons/w_missile_closed.mdl"
ITEM.ammo = "PG-7VM Grenade"
ITEM.ammoAmount = 1
ITEM.description= "PG-7VM Grenade, a rocket propelled grenade. It shears through metal with a shaped charge. Basically messes up anything it comes in contact with."
ITEM.isAmmo = true
ITEM.category = "Ammunition"
ITEM.ammoPerBox = 1
ITEM.price = 5000
ITEM.weight = 6