ITEM.name = "VOG-25 Grenade"
ITEM.model = ("models/Items/AR2_Grenade.mdl")
ITEM.description = "VOG-25 Grenade, made specifically to be launched from Warsaw Grenade Launchers."
ITEM.category = "Ammunition"
ITEM.ammo = "40MM"
ITEM.ammoAmount = 3
ITEM.isAmmo = true
ITEM.ammoPerBox = 1
ITEM.price = 1500
ITEM.weight = 0.42