ITEM.name = "King Arms MR"
ITEM.description = "Taiwanese reflex sight. T type sight."
ITEM.category = "Attachments"
ITEM.width = 1
ITEM.height = 1
ITEM.attSearch = { "md_reflex",}
ITEM.model = "models/cw2/attachments/microt1.mdl"
ITEM.slot = 1
ITEM.isAttachment = true