ITEM.name = "Arrow"
ITEM.description = "Named for its shape, the arrow appears as an oddly shaped spike.  When held, an Arrow will pull foreign bodies such as bullets or sharpnel in nearby wounds slowly towards it, following the path of its entry wound..  The artifact also gives off a moderate amount of radiation. [+4 RAD]"
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/ice.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.2
ITEM.isArtefact = true;
ITEM.price = 70000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 4