ITEM.name = "Fireball"
ITEM.model ="models/nasca/etherealsrp_artifacts/fireball.mdl"
ITEM.description = "A ball of fire. Artifact."
ITEM.longdesc = "Consumes excess heat in its surroundings, converting the energy into a minor amount of ionizing radiation. Maintains a constant temperature of 23° Celsius / 75° Fahrenheit. [ +3 BURN | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4600
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 0.7
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.03,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}