ITEM.name = "Fountain"
ITEM.description = "A layered fountain formation"
ITEM.longdesc = "An artifact of gravitational nature. It does not have any useful properties, but because of it's bizarre shape it is valued by collectors. Is not radioactive."
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/fountain.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.4
ITEM.isArtefact = true
ITEM.price = 5100
ITEM.flag = "A"