ITEM.name = "Gravi"
ITEM.model = "models/nasca/etherealsrp_artifacts/gravi.mdl"
ITEM.description = "Lumpy, reddish artifact."
ITEM.longdesc = "Emits a moderate amount of radiation whilst increasing the carry weight of the one holding the artifact. Affects the inner ear's function, causing lightheadedness, dizziness, and nausea. [ +8kg WEIGHT | +3 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 47250
ITEM.flag = "A" 
ITEM.buff = "weight"
ITEM.buffval = 8
ITEM.debuff = "rads"
ITEM.debuffval = 3
ITEM.isArtefact = true
ITEM.weight = 0.85