ITEM.name = "Meatchunk"
ITEM.model ="models/nasca/etherealsrp_artifacts/meatchunk.mdl"
ITEM.description = "Looks like flayed skin. Artifact."
ITEM.longdesc = "Emits a minor amount of radiation and provides a moderate amount of protection against caustics. Increased production of mucus from nostrils. [ +4 CHEM | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 12500
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.04,
	["Psi"] = 0.00,
}
ITEM.weight = 2.4;