ITEM.name = "Mica"
ITEM.model = "models/nasca/etherealsrp_artifacts/mica.mdl"
ITEM.description = "Brown artifact."
ITEM.longdesc = "Increases the rate at which blood coagulates around wounds quite notably. In doing this, the user becomes quite exhausted. Those who use it regularly note that they sleep longer and deeper, and experience cold-like symptoms in regards to mucus production. [ +4 WH | -4 STAM]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 50000
ITEM.flag = "A"
ITEM.buff = "woundheal"
ITEM.buffval = 4
ITEM.debuff = "end"
ITEM.debuffval = 4
ITEM.isArtefact = true
ITEM.weight = 0.6;