ITEM.name = "Mama's beads"
ITEM.model ="models/nasca/etherealsrp_artifacts/mamas_beads.mdl"
ITEM.description = "Helix-shaped, pulsating artifact."
ITEM.longdesc = "Effectively heals minor wounds, and can heal large wounds over a long period of time. Emits insignificant radiation. Initial skin discoloration upon healing, effect reduces over time. [ +2 WH | +1 RAD]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 33250
ITEM.flag = "A"
ITEM.buff = "woundheal"
ITEM.buffval = 2
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 1.3;