ITEM.name = "Snowflake"
ITEM.model ="models/nasca/etherealsrp_artifacts/snowflake.mdl"
ITEM.description = "This artifact features blue spikes."
ITEM.longdesc = "Emits a moderate amount of radiation, in return increases the bearer's muscle tone significantly. Constant vibration of the user’s body that some stalkers have reported feeling “Cold” or “Chilly”. Constant use can lead to muscle fatigue. [ +6 STAM | +3 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 38000
ITEM.flag = "A"
ITEM.buff = "end"
ITEM.buffval = 6
ITEM.debuff = "rads"
ITEM.debuffval = 3
ITEM.isArtefact = true
ITEM.weight = 3.2;