ITEM.name = "Sandstone"
ITEM.description = "A bumpy orb."
ITEM.longdesc = "Formed in zones with extreme temperatures. Has no useful properties and is not radioactive, but does contain a small amount of gold lending it some value."
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/sandstone.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.6
ITEM.isArtefact = true
ITEM.price = 2750
ITEM.flag = "A"