ITEM.name = "Thorn"
ITEM.model ="models/nasca/etherealsrp_artifacts/crystal_thorn.mdl"
ITEM.description = "Spikey artifact, but quite small."
ITEM.longdesc = "Draws out radiation through the use of pricking the user’s skin, no matter if armor is worn or not. When worn will cause bleeding. [ -1 RAD | -1 WH ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.flag = "A"
ITEM.buff = "antirad"
ITEM.buffval = 1
ITEM.isArtefact = true
ITEM.weight = 0.3