ITEM.name = ".357 Magnum"
ITEM.model = "models/Items/357ammo.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = ".357"
ITEM.description = "A Box that contains .357 Magnum"
ITEM.category = "Ammunition"
ITEM.ammoAmount = 100
ITEM.isAmmo = true