ITEM.name = "5.56x45mm"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "5.56x45MM"
ITEM.ammoAmount = 100
ITEM.description = "A standard-issue NATO 5.56x45 caliber round specially designed for accurate automatic fire. Provides good ballistic characteristics, having been designed on the basis of a hunting round."
ITEM.isAmmo = true
ITEM.category = "Ammunition"