ITEM.name = "7.62x54mm Belt"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x54MMB"
ITEM.description = "A Belt of 7.62x54mmR"
ITEM.category = "Ammunition"
ITEM.ammoAmount = 100
ITEM.isAmmo = true