ITEM.name = "7.62x54mm"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x54MMR"
ITEM.ammoAmount = 100
ITEM.description = "Cheap 7.62 PP (also known as 7.62 R) is a dated rifle caliber introduced in the Soviet Empire at the turn of the 19th century and was still used by the USSR after World War II."
ITEM.width = 2
ITEM.height = 1
ITEM.isAmmo = true
ITEM.category = "Ammunition"