ITEM.name = "Battery"
ITEM.model ="models/nasca/etherealsrp_artifacts/battery.mdl"
ITEM.description = "An electric artifact."
ITEM.longdesc = "Stimulates the production of ATP in human cells, reducing fatigue and giving a decent boost to stamina recovery. Emits a moderate amount of radiation. Causes short term insomnia. [ +3 STAM | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8100
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.buff = "end"
ITEM.buffval = 3
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.weight = 0.4