ITEM.name = "Bubble"
ITEM.model ="models/nasca/etherealsrp_artifacts/bubble.mdl"
ITEM.description = "A green artifact."
ITEM.longdesc = "Emits a passive, gaseous substance that neutralizes radioactive particles inside the body. Side Effects: Causes continual buildup of gaseous activity within the body, thus causing occasional flatulence and belching. [ -5 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 69750
ITEM.flag = "A"
ITEM.buff = "antirad"
ITEM.buffval = 6
ITEM.isArtefact = true
ITEM.weight = 0.7