ITEM.name = "Bat"
ITEM.description = "A sphere surrounded in veins and wings."
ITEM.longdesc = "A very beautiful abnormal formation. Has no useful properties, not radioactive and quite heavy. Valued by collectors."
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/bat.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 6
ITEM.isArtefact = true
ITEM.price = 2000
ITEM.flag = "A"