ITEM.name = "Bracelet"
ITEM.description = "A cylinder with decorative lines."
ITEM.longdesc = "An artifact of chemical nature, and appears similar to leaves intertwined and petrified yet feels organic to the touch. It provides substantial protection against all types of acids by gradually increasing their pH to the level of water. When worn, the artifact is also known to slightly counter the harmful effects of psy-anomalies and psy-waves of some mutants. [ +2 PSY, +2 CHEM | +2 RAD ]"
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/black_angel.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.3
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.price = 4250
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.02,
}
ITEM.flag = "A"