ITEM.name = "Crystal"
ITEM.model ="models/nasca/etherealsrp_artifacts/crystal.mdl"
ITEM.description = "A crystal-like artifact."
ITEM.longdesc = "Emits a minor amount of radiation and actively consumes nearby excess heat. Maintains an internal temperature, providing a small amount of warmth under 15 Celsius. [ +1 BURN | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2400
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 0.6
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.01,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}