ITEM.name = "Eye"
ITEM.model ="models/nasca/etherealsrp_artifacts/eye.mdl"
ITEM.description = "This artifact looks like an eye."
ITEM.longdesc = "Emits a moderate amount of radiation. Locally accelerates the body's metabolism, boosting the production of blood clots and scar tissue. Increased production of endorphins; addiction is a possibility. [ +3 WH | +2 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 49250
ITEM.flag = "A"
ITEM.buff = "woundheal"
ITEM.buffval = 4
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 1.1