ITEM.name = "Flash"
ITEM.model = "models/nasca/etherealsrp_artifacts/flash.mdl"
ITEM.description = "This artifact emits a lot of light."
ITEM.longdesc = "Emits a minor amount of radiation and provides moderate protection against electric energy. Moderate increase of constant static electricity generated from the user. [ +3 SHOCK | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10500
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.03,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 0.2