ITEM.name = "Firefly"
ITEM.model ="models/nasca/etherealsrp_artifacts/firefly.mdl"
ITEM.description = "Green and beautiful artifact."
ITEM.longdesc = "Considerably speeds up regeneration of tissue and organs in living beings, as well as normalizing metabolic processes. Cannot regrow or accelerate healing of bones. [ +6 HEAL | +4 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 88500
ITEM.flag = "A"
ITEM.buff = "heal"
ITEM.buffval = 6
ITEM.debuff = "rads"
ITEM.debuffval = 4
ITEM.isArtefact = true
ITEM.weight = 2.5