ITEM.name = "Flame"
ITEM.model = "models/nasca/etherealsrp_artifacts/flame.mdl"
ITEM.description = "Flaming artifact."
ITEM.longdesc = "Speeds up the metabolic process similar to the Eye, quickly restoring damaged tissue. Emits a dangerous amount of radiation. Side Effect: Skin becomes sensitive. Regulates heat. [ +6 WH | +3 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 56000
ITEM.flag = "A"
ITEM.buff = "woundheal"
ITEM.buffval = 6
ITEM.debuff = "rads"
ITEM.debuffval = 3
ITEM.isArtefact = true
ITEM.weight = 0.9