ITEM.name = "Goldfish"
ITEM.model = "models/nasca/etherealsrp_artifacts/goldfish.mdl"
ITEM.description = "Golden, beautiful artifact."
ITEM.longdesc = "Produces a gravitational field that increases the carry weight of the user holding the artifact. Results in a feeling of weightlessness; dizziness and nausea follow soon after. Emits a moderate amount of radiation. [ +12kg WEIGHT | +3 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 71500
ITEM.flag = "A"
ITEM.buff = "weight"
ITEM.buffval = 12
ITEM.debuff = "rads"
ITEM.debuffval = 3
ITEM.isArtefact = true
ITEM.weight = 1.7