ITEM.name = "Jellyfish"
ITEM.model = "models/nasca/etherealsrp_artifacts/jellyfish.mdl"
ITEM.description = "Cone artifact. Brown in appearance."
ITEM.longdesc = "Draws out radiation through an anomalous field. Side Effect: Causes yellowing of the sclera (Whiter outside of eyes). Prolonged use causes temporary blindness. [ -1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1250
ITEM.flag = "A"
ITEM.buff = "antirad"
ITEM.buffval = 1
ITEM.isArtefact = true
ITEM.weight = 0.5