ITEM.name = "Lobster Eyes"
ITEM.description = "Two eye shaped lumps"
ITEM.longdesc = "Formed in the shape of 2 eyes fused together. The outer surface is very thick, and the high density of its formation might be the reason behind its deep color. This artifact offers slightly more burn resistance than it's cousin, the Crystal. It resonates under influence of heat, and seems to absorb it while staying cool to the touch. [ +2 BURN | +2 RAD ]"
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/tapeworm.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 3
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.price = 3400
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.02,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.flag = "A"