ITEM.name = "Moonlight"
ITEM.model = "models/nasca/etherealsrp_artifacts/moonlight.mdl"
ITEM.description = "Light emits from this artifact."
ITEM.longdesc = "Protects the user from psionic radiation rather effectively. Initial use causes tiredness within the user, prolonged use causes microsleeps. [ +3 PSY | +2 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 52500
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.03,
}
ITEM.weight = 3;