ITEM.name = "Nightstar"
ITEM.model ="models/nasca/etherealsrp_artifacts/nightstar.mdl"
ITEM.description = "Spikey yellow artifact. Glowing."
ITEM.longdesc = "Emits a small amount of radiation. Emits a small gravity field that increases the carry weight of anyone using it. Causes the user to no longer experience nightmares. [ +4kg WEIGHT | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 9150
ITEM.flag = "A"
ITEM.buff = "weight"
ITEM.buffval = 4
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 2