ITEM.name = "Spring"
ITEM.description = "Emits a gravitation field that slows incoming objects, including bullets. Reduces incoming projectile force by around thirty percent. [ +15 IMP ]"
ITEM.category = "Artifacts"
ITEM.model = "models/nasca/etherealsrp_artifacts/shell.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.5
ITEM.isArtefact = true
ITEM.price = 80000
ITEM.flag = "A"
ITEM.res = {
	["Fall"] = 0.15,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 3.5