ITEM.name = "Screw"
ITEM.description = "The Screw artifact is a strangely rare utility artifact, found only on occasion. Its purpose is to screw and unscrew, as well as hammer. It will work on any screws or nails that are not beyond the normal limitations of hand tools, and must be in direct contact with them. By some unfathomable stroke of anomalous properties, it will refuse to function unless the owner(s) of the structure involved have completely abandoned it, died, or the owner(s) themselves are using the artifact. Any attempt to use it otherwise will result in a loud ratcheting sound. Stalkers have noted that it will also open pickle jars."
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/grib.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.8
ITEM.isArtefact = true
ITEM.price = 30000
ITEM.flag = "A"