ITEM.name = "Shell"
ITEM.model = "models/nasca/etherealsrp_artifacts/shell.mdl"
ITEM.description = "Blue, semit-ransparent artifact."
ITEM.longdesc = "During prolonged use, the Shell stimulates the nervous system to increase energy recovery. This effect surpasses the Battery's. Up until recently was considered a trash artifact, devoid of any useful properties. Emits a moderate amount of radiation. Constant build up of stimulation to the nervous system can be fatal to the user. Senses continue to heighten into painful spasms. [ +4 STAM, +1 PSY | +2 RAD -5 CHEM ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 16500
ITEM.flag = "A"
ITEM.buff = "end"
ITEM.buffval = 4
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 2