ITEM.name = "Stone Flower"
ITEM.model ="models/nasca/etherealsrp_artifacts/stoneflower.mdl"
ITEM.description = "Looks like its melted and ripped apart. Artifact."
ITEM.longdesc = "Emits a minor amount of radiation and protects against psionic radiation. [ +1 PSY | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3900
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.01,
}
ITEM.weight = 1.3