ITEM.name = "Slime"
ITEM.model ="models/nasca/etherealsrp_artifacts/slime.mdl"
ITEM.description = "Slimey."
ITEM.longdesc = "User feels, on average, healthier thanks to increased nutrients. [ +1 WH | +2 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2250
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.buff = "woundheal"
ITEM.buffval = 1
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.weight = 0.9