ITEM.name = "Signet"
ITEM.description = "An interwoven and complex amalgamation."
ITEM.longdesc = "Some stalkers call this artifact the 'Amulet'. Quite useless, yet some stalkers believe that this artifact brings good luck. Not radioactive."
ITEM.category = "Artifacts"
ITEM.model = "models/artefacts/signet.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.6
ITEM.isArtefact = true
ITEM.price = 1300
ITEM.flag = "A"