ITEM.name = "Soul"
ITEM.model ="models/nasca/etherealsrp_artifacts/soul.mdl"
ITEM.description = "Spherish, blue artifact."
ITEM.longdesc = "Restores damaged tissue and wounds slowly. Long-term use can result in short-term paranoia. [ +2 HEAL | +2 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 41250
ITEM.flag = "A"
ITEM.buff = "heal"
ITEM.buffval = 2
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 2.2