ITEM.name = "Sparkler"
ITEM.model ="models/nasca/etherealsrp_artifacts/sparkler.mdl"
ITEM.description = "Silky in appearance. Artifact."
ITEM.longdesc = "Emits a minor amount of radiation and absorbs a minor amount of electricity. Can power small devices. Causes the user to generate static electricity at an increased rate. [ +1 SHOCK | +1 RAD ]"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1700
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.01,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 0.75